name: 7030_class_1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - ipykernel
  - nbconvert
  - pandas
  - matplotlib
  - scikit-learn
  - numpy
  - r-base
  - r-irkernel
  - r-ggplot2
